### ISSUE TITLE
How to translate labels and placeholders to inputs

### ISSUE THREAD

**Issue by danieldocki** [solid-process/solid-process#8]
I tried through the Rails convention and couldn't. What can it be?

Example:

```ruby
class User::Creation < Solid::Process
  input do
    attribute :name
    attribute :email
  end

  def call(attributes)
    # ...
  end
end
```

```yaml
pt-BR:
  helpers:
    label:
      user:
        creation:
          input:
            name: Nome
            email: E-mail
    placeholder:
      user:
        creation:
          input:
            name: Digite seu nome
            email: Digite seu e-mail
 ```
 
 ```erb
 input = User::Creation::Input.new

<%= form_with(model: input, url: url) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>
<% end %>
```

**Comment by serradura** [comment]
Hi @danieldocki, how are you? Thank you for posting your question.

You need to define the key name as the output of the `model_name.i18n_key`. 

```ruby
User::Creation::Input.model_name.i18n_key
# :"user/creation/input"
```

```yaml
pt-BR:
  helpers:
    label:
      "user/creation/input":
        name: Nome
        email: E-mail
    placeholder:
      "user/creation/input":
        name: Digite seu nome
        email: Digite seu e-mail
```

See below an example I made using the [Solid Rails App](https://github.com/solid-process/solid-rails-app):

<img width="2052" alt="bin_rails_c_and_Solid_Rails_and_en_yml_—_solid-rails-app_and__form_html_erb_—_rails-way-app_and_Notes" src="https://github.com/user-attachments/assets/ece6195a-d551-4af0-89fc-7a876057b8d5">
